### ISSUE TITLE
可以指导下安装吗？可偿

### ISSUE THREAD

**Issue by VapeSeven** [Jasper-1024/mosdns_docker#1]
我运行docker compose的时候，提示mosdns没有unofficial镜像

**Comment by Jasper-1024** [comment]
排查问题 请提供 尽可能多的信息 log 截图等等, 否则我想帮忙也无从下手啊.

**Comment by VapeSeven** [comment]
可以远程安装演示一遍嘛？



---- 回复的原邮件 ----
| 发件人 | Jasper ***@***.***> |
| 日期 | 2024年06月06日 22:01 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Jasper-1024/mosdns_docker] 可以指导下安装吗？可偿 (Issue #1) |

排查问题 请提供 尽可能多的信息 log 截图等等, 否则我想帮忙也无从下手啊.

**Comment by VapeSeven** [comment]
loki的没有数据
