### ISSUE TITLE
geosite_gfw域名未转发

### ISSUE THREAD

**Issue by moreoronce** [Jasper-1024/mosdns_docker#2]
目前config文件里的sequence都没有匹配geosite_gfw规则提交给forward_remote进行转发解析。在这种情况下，遇到已经黑名单的域名会同时先用dns_cn进行解析，然后用dns_nocn进行解析，延迟增加且会有泄露可能。 

在nextdns的log里可以看到我的机场IP和本地IP都在请求。我自己尝试增加sequence，但是增加之后grafana的数据就没有了，希望可以解决。谢谢

**Comment by Jasper-1024** [comment]
> 目前config文件里的sequence都没有匹配geosite_gfw规则提交给forward_remote进行转发解析。在这种情况下，遇到已经黑名单的域名会同时先用dns_cn进行解析，然后用dns_nocn进行解析，延迟增加且会有泄露可能。
> 
> 在nextdns的log里可以看到我的机场IP和本地IP都在请求。我自己尝试增加sequence，但是增加之后grafana的数据就没有了，希望可以解决。谢谢

我理解这里说的 是属于 geosite_gfw 的域名,  处理流程有问题?
如果能 来个例子 就更清楚了.
这个周末会详细看看

**Comment by moreoronce** [comment]
嗯， 说的就是处理流程的事情。 不过我已经自己加上sequence解决问题了。

下午Grafana空白的问题，估计应该是因为我修改配置文件之后没注意语法检查，漏掉空格一类导致的启动失败。 谢谢

**Comment by Jasper-1024** [comment]
直到今天重新问了一下 cursor 才知道 gfw 流程忘写了 🥲 一直以为流程在那，所以完全看不懂问题。
